### PR TITLE
[WIP] Convert this to an about.yml copier

### PR DESCRIPTION
**Pull request by toolness**
This is a foolhardy attempt to convert team-api-server into a much simpler tool that just waits for GitHub webhook notifications from other 18F repos and copies their `.about.yml`'s to `_data/projects/<project-name>.yml` in the [team-api.18f.gov](https://github.com/18F/team-api.18f.gov) repo using the GitHub API.

This means:

* No more serving static files built from team-api.18f.gov. We'll move that over to a [cloud.gov `staticfile-buildpack`](https://docs.cloud.gov/apps/static/), which will be pushed-to by a travis `after_success` hook on team-api.18f.gov.

* No more calling `git` from the command-line on the server-side. We'll use GitHub's API directly.

The above means that we remove ruby and git as dependencies, making this a pretty straightforward node app that can be deployed to cloud.gov via its [node buildpack](https://docs.cloud.gov/apps/node/).

### Setup

In order to use this, the following environment variables need to be defined:

* `GITHUB_USERNAME` - The GitHub user that will authenticate with the GitHub API.
* `GITHUB_PASSWORD` - The password used to authenticate with the GitHub API. Note that this should really be a [personal access token](https://github.com/blog/1509-personal-api-tokens) with [`repo` scope](https://developer.github.com/v3/oauth/#scopes).

### To do

- [X] `github-file-client.js` uses callbacks, but existing code in this project uses promises, so we should convert it to use promises too.
- [ ] Add tests for `github-file-client.js`.
- [ ] Change `project-data-updater.js` to just listen for webhooks from other repos and copy the `.about.yml`.
- [ ] Get rid of `team-api-config.json` and [store config in the environment](http://12factor.net/config) for easy cloud.gov deployment.
- [ ] It'd be nice, but not *necessary*, if the [`author`](https://developer.github.com/v3/repos/contents/#optional-parameters) of each copied file was the same as the author of the `.about.yml` change that triggered the webhook. Or if the commit message of the automated commit included a link to the commit that triggered the webhook. Anything to provide some context around causality.

### CODE REVIEW

**Comment by toolness** [comment]
Also, my apologies in advance for my terrible node code ... I haven't used node in a long time and the `package.json` says node 0.12 so I'm not using any fancy ES6 stuff. 😣 Suggestions welcome!

**Comment by toolness** [comment]
@afeld, does the "Setup" section above look OK to you from a security standpoint? Or should we be using a different mechanism to authenticate with the GitHub API?

**Comment by jseppi** [comment]
Cloud.gov supports node 5.10.0 and will likely support 6.1.0 soonish, so you could upgrade this project to use at least features in node 5.10. Handy chart of supported features: http://node.green/

**Comment by toolness** [comment]
This is superseded by #14!

**Pull request closed without merging**
